development:
  adapter: mysql2
  encoding: utf8
  database: SCHEDULE
  pool: 5
  username: lab2
  password: 10
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: SCHEDULE
  pool: 5
  username: lab2
  password: 10
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: SCHEDULE
  pool: 5
  username: lab2
  password: 10
  socket: /var/run/mysqld/mysqld.sock